apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus.name" . }}
  annotations:
    prometheus.io/scrape: {{ .Values.service.scrape | quote }}
    prometheus.io/path: {{ .Values.service.path | quote }}
    prometheus.io/port:  {{ .Values.service.port | quote }}
spec:
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: {{ template "prometheus.name" . }}
  selector:
    app: {{ template "prometheus.name" . }}
