# Default values for prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

service:
  port: 9090
  path: /metrics
  scrape: 'true'
ingress:
  host: prometheus.myproject.com

securityContext:
  fsGroup: 1000
terminationGracePeriodSeconds: 10

init:
  image:
    repository: busybox
    tag: {}
  resources:
    limits:
      cpu: 10m
      memory: 10Mi
    requests:
      cpu: 1m
      memory: 5Mi

prometheus:
  image:
    repository: prom/prometheus
    tag: v2.9.2
  configFile: /etc/prometheus/prometheus.yml
  storageTsdbPath: /prometheus
  retention: 15d
  logFormat: json
  resources: 
    requests:
      cpu: 2000m
      memory: 2Gi
    limits:
      cpu: 4000m
      memory: 8Gi
  resources:
    limits:
      cpu: 10m
      memory: 10Mi
    requests:
      cpu: 1m
      memory: 5Mi
prometheusController:
  image:
    repository: dockerregistry/prometheus-config-controller
    tag: 1.0.0
  url: "http://localhost:9090/-/reload"
  id: "0"
  path: "/etc/config"
  template: "/etc/prometheus/prometheus.tmpl"
  logLevel: "info"
volumeClaimTemplates:
  name: data
  accessModes: [ "ReadWriteOnce" ]
  requests:
    storage: 100Gi

